version: "3.5"

services:
  database:
    image: "postgres:12.6-alpine"
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT_NUMBER}:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: twt_clone_database
    volumes:
      - twt_clone_pgdata:/var/lib/postgresql/data
    networks:
      - twt_clone
    restart: unless-stopped
  
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
      
  certbot:
    image: certbot/certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot

  # redis:
  #   image: "bitnami/redis:5.0"
  #   container_name: twt_clone_redis
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes #is recommended only for development.
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #   ports:
  #     - "${REDIS_PORT_NUMBER}:${REDIS_PORT_NUMBER}"
  #   volumes:
  #     - "redis_data:/bitnami/redis/data"
  #   networks:
  #     - twt_clone

volumes:
  redis_data:
  twt_clone_pgdata:

networks:
  twt_clone:
    name: twt_clone
